-- Sticker shop seal currencies (N / R / P / SEC / PR).
--
-- N/R/P/SEC were ensured during bootstrap / earlier deploys.
-- PR is applied by tcgDbRunMigrationOnce('seal_pr_column_20260730') in db.php
-- (bootstrap_v2 skips ensure-columns; this file is intentionally documentation-only
-- so Migrator does not run a bare ALTER that can fail if the column already exists).
