-- Per-preset card sleeve (cosmetic). Empty string = default official back.
-- Applied via tcgDbRunMigrationOnce('deck_sleeves_20260812') in db.php on boot.
-- Do not ALTER here: production DBs already have bootstrap_v2, and a failing
-- Migrator::exec on this file would 500 every account.php request.
